image: maven:3.8.7-openjdk-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - package

cache:
  paths:
    - .m2/repository

build_job:
  stage: build
  script:
    - mvn compile
  only:
    - main
    - develop

test_job:
  stage: test
  script:
    - mvn test
  only:
    - main
    - develop

package_job:
  stage: package
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  only:
    - main
    - develop