image: maven:3.9.2-jdk-21  # valid Docker Hub image

stages:
  - build
  - test
  - package
  - artifact

build:
  stage: build
  script:
    - echo "Building project..."
    - mvn clean compile
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

package:
  stage: package
  script:
    - echo "Packaging project..."
    - mvn package
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

artifact:
  stage: artifact
  script:
    - echo "Saving artifact..."
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'