image: maven:3.9.2-eclipse-temurin-21

stages:
  - build
  - test
  - package
  - artifact

# Build Stage
build:
  stage: build
  script:
    - echo "Building project..."
    - mvn clean compile
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Test Stage
test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Package Stage
package:
  stage: package
  script:
    - echo "Packaging project..."
    - mvn package
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Artifact Stage
artifact:
  stage: artifact
  script:
    - echo "Saving artifact..."
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'